services:
  server:
    build:
      context: .
    ports:
      - 80:80
    environment:
      SERVER_PORT: 80
      URL_PRODUCT: https://rgr3viiqdl8sikgv.public.blob.vercel-storage.com/produtos-mnboX5IPl6VgG390FECTKqHsD9SkLS.json
      URL_CLIENTS_PURCHASES: https://rgr3viiqdl8sikgv.public.blob.vercel-storage.com/clientes-Vz1U6aR3GTsjb3W8BRJhcNKmA81pVh.json